server.port: 8081
#file.storage.location: fileStorage

spring:
  servlet:
    multipart:
      enabled: true
      location: temp123
      file-size-threshold: 5MB
      max-file-size: 5MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://localhost:3306/fileupload
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver